version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: ultiproxy-backend-prod
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=warn
    volumes:
      - ./config:/app/config:ro
      - ./examples:/app/examples:ro
    networks:
      - ultiproxy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  frontend:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
      target: runtime
    container_name: ultiproxy-frontend-prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ultiproxy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
  ultiproxy-network:
    driver: bridge
    name: ultiproxy-network-prod