version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ultiproxy-backend
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    volumes:
      - ./config:/app/config:ro
      - ./examples:/app/examples:ro
    networks:
      - ultiproxy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://backend:8080
    container_name: ultiproxy-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ultiproxy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  ultiproxy-network:
    driver: bridge
    name: ultiproxy-network